feat: Clean-deploy-pipeline (#14)
* better names for stages

* fix postman tests checks

* updated postman runs checks

* debug

* debug

* debug

* try only postman

* try only postman

* fix func

* try all

* try all

* try all

* pre-commit fixs

diff --git a/.devops/deploy.yml b/.devops/deploy.yml
--- a/.devops/deploy.yml
+++ b/.devops/deploy.yml
@@ -4,7 +4,7 @@ pr:
   branches:
     include:
       - main
-  paths:  
+  paths:
     include:
     - 'helm/dev/**'
 
@@ -17,8 +17,8 @@ schedules:
   always: true
 
 parameters:
-- name: ENV 
-  displayName: Environment 
+- name: ENV
+  displayName: Environment
   type: string
   default: dev
   values:
@@ -26,14 +26,14 @@ parameters:
     - uat
     - prod
 
-- name: APPS 
-  displayName: ArgoCD Apps 
+- name: APPS
+  displayName: ArgoCD Apps
   type: object
   default:
     - one-color
     - two-color
 
-- name: POSTMAN_BRANCH 
+- name: POSTMAN_BRANCH
   displayName: Postman branch
   type: string
   default: 'develop'
@@ -41,7 +41,7 @@ parameters:
 variables:
   - name: directoryPattern
     value: 'helm/${{ parameters.ENV }}'
-  - name: isCompleteRun
+  - name: isPullRequestTrigger
     value: $[eq(variables['Build.Reason'], 'PullRequest')]
   - name: System.Debug
     value: true
@@ -58,8 +58,18 @@ pool:
   vmImage: ubuntu-latest
 
 stages:
-  - stage: PrGitChangedFolders
-    condition: and(succeeded(), eq(variables.isCompleteRun, false))
+  - stage: debug
+    condition: succeeded()
+    jobs:
+    - job: debug_steps
+      pool:
+        vmImage: 'ubuntu-latest'
+      steps:
+      - script: |
+          echo  "build reason:  ${{variables['Build.Reason']}}"
+
+  - stage: calculate_pr_git_changes
+    condition: and(succeeded(), eq(variables.isPullRequestTrigger, true))
     jobs:
     - job: FindGitChangedFolder
       pool:
@@ -69,67 +79,68 @@ stages:
         fetchDepth: 0
         name: checkoutCode
         displayName: 'Checkout Code'
-  
+
       - task: UsePythonVersion@0
         inputs:
           versionSpec: '3.x'
           addToPath: true
         name: setupPython
         displayName: 'Setup Python'
-  
+
       - task: PythonScript@0
-        name: GrepGitFolders
+        name: grep_git_folders
         displayName: 'Process String and Convert to JSON'
         inputs:
           scriptSource: 'inline'
           script: |
             import json
             import subprocess
-            
+
             print("Starting the process...")
-            
+
             command = "git diff --name-only --diff-filter=d origin/main...HEAD | xargs -I {} dirname {} | sort -u"
             print(f"Executing command: {command}")
-            
+
             str = subprocess.check_output(command, shell=True).decode('utf-8').strip()
             print(f"Command output: {str}")
-            
+
             filtered_list = [item for item in str.split('\n') if "helm/dev" in item]
             print(f"Filtered list: {filtered_list}")
-            
+
             cleaned_list = [item.replace("helm/dev/", "") for item in filtered_list]
             print(f"Cleaned list: {cleaned_list}")
-            
+
             result_json = json.dumps(cleaned_list)
             print(f"Final JSON result: {result_json}")
-            
+
             print(f'##vso[task.setvariable variable=resultJson;isOutput=true]{result_json}')
             print("Process completed.")
 
       - task: Bash@3
-        name: EchoResultJson
+        name: EchoBashJson
         displayName: 'Echo Result JSON Array'
         inputs:
           targetType: 'inline'
           script: |
             echo "Risultato JSON Array:"
-            echo '$(GrepGitFolders.resultJson)'
-            echo "##vso[task.setvariable variable=savedResultJsonArray;isOutput=true]$(GrepGitFolders.resultJson)"
+            echo '$(grep_git_folders.resultJson)'
+            echo "##vso[task.setvariable variable=savedResultJsonArray;isOutput=true]$(grep_git_folders.resultJson)"
 
-  - stage: ProcessItems
-    dependsOn: 
-      - PrGitChangedFolders
+  - stage: sync_argo_apps
+    dependsOn:
+      - calculate_pr_git_changes
     condition: always()
     variables:
-      ${{ if eq(variables.isCompleteRun, false) }}:
-        resultJsonArrayPython: $[ stageDependencies.PrGitChangedFolders.FindGitChangedFolder.outputs['GrepGitFolders.resultJson'] ]
-        resultJsonArrayBash: $[ stageDependencies.PrGitChangedFolders.FindGitChangedFolder.outputs['EchoResultJson.savedResultJsonArray'] ]
+      ${{ if eq(variables.isPullRequestTrigger, true) }}:
+        resultJsonArrayPython: $[ stageDependencies.calculate_pr_git_changes.FindGitChangedFolder.outputs['grep_git_folders.resultJson'] ]
+        resultJsonArrayBash: $[ stageDependencies.calculate_pr_git_changes.FindGitChangedFolder.outputs['EchoBashJson.savedResultJsonArray'] ]
       ${{ else }}:
         resultJsonArrayPython: '${{ convertToJson(parameters.APPS) }}'
         resultJsonArrayBash: '${{ convertToJson(parameters.APPS) }}'
     jobs:
     - deployment: update_root_app
-      pool: 
+      displayName:  Update Argocd root app
+      pool:
         name: $(DEV_AGENT_POOL)
       environment: ${{ parameters.ENV }}
       strategy:
@@ -137,8 +148,8 @@ stages:
           deploy:
             steps:
             - bash: |
-                echo "Is this a complete run? $(isCompleteRun)"
-                echo "Is this a complete run? ${{variables.isCompleteRun}}"
+                echo "Is this a complete run? $(isPullRequestTrigger)"
+                echo "Is this a complete run? ${{variables.isPullRequestTrigger}}"
                 echo "---"
                 echo "BuildReason: ${{variables['Build.Reason']}} "
                 echo "Changed applications:"
@@ -151,7 +162,7 @@ stages:
                 # Login to ArgoCD
                 curl -sSL -o /tmp/argocd-v2.12.4 https://github.com/argoproj/argo-cd/releases/download/v2.12.4/argocd-linux-amd64
                 chmod +x /tmp/argocd-v2.12.4
-                sudo mv /tmp/argocd-v2.12.4 /usr/local/bin/argocd 
+                sudo mv /tmp/argocd-v2.12.4 /usr/local/bin/argocd
 
                 argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure --grpc-web
 
@@ -161,32 +172,22 @@ stages:
               name: displayChangedAppsAndSyncRoot
               displayName: 'Display Changed Apps and Sync Root App'
 
-    - job: CheckRepositoryTrigger
-      displayName: 'Check Repository Trigger'
-      dependsOn: update_root_app
-      condition: succeeded()
-      steps:
-      - bash: |
-          echo "Triggered by repository: $(Build.Repository.Name)"
-        name: displayTriggerRepo
-        displayName: 'Display Trigger Repository Info'
-          
     - ${{ each item in parameters.APPS }}:
       - deployment: deploy_${{ replace(item, '-', '_') }}
         displayName: 'Deploy ${{ item }}'
-        pool: 
+        pool:
           name: $(DEV_AGENT_POOL)
         environment: ${{ parameters.ENV }}
-        dependsOn: [update_root_app, CheckRepositoryTrigger]
+        dependsOn: [update_root_app]
         condition: >
           and(
             succeeded(),
             or(
               and(
-                eq(variables.isCompleteRun, false),
+                eq(variables.isPullRequestTrigger, false),
                 contains(variables.resultJsonArrayPython, '${{ item }}')
               ),
-              eq(variables.isCompleteRun, true)
+              eq(variables.isPullRequestTrigger, true)
             )
           )
         strategy:
@@ -202,14 +203,14 @@ stages:
                   # Login to ArgoCD
                   curl -sSL -o /tmp/argocd-v2.12.4 https://github.com/argoproj/argo-cd/releases/download/v2.12.4/argocd-linux-amd64
                   chmod +x /tmp/argocd-v2.12.4
-                  sudo mv /tmp/argocd-v2.12.4 /usr/local/bin/argocd 
+                  sudo mv /tmp/argocd-v2.12.4 /usr/local/bin/argocd
 
                   argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure --grpc-web
 
                   # Sync the app
                   app_name=${{ item }}
                   argocd app sync "$app_name" --prune
-                  
+
                   argocd app actions run "$app_name" restart --kind Deployment --all --grpc-web
 
                   echo "✅ Syncing app: $app_name"
@@ -220,111 +221,139 @@ stages:
                   ARGOCD_USERNAME: $(argocdUsername)
                   ARGOCD_PASSWORD: $(argocdPassword)
 
-  - stage: check_postman_test
+  - stage: postman_tests
     displayName: Check and run postman tests
-    dependsOn: [ProcessItems]
-    condition: succeeded()
+    dependsOn: [sync_argo_apps]
+    condition: always()
     jobs:
       - ${{ each item in parameters.APPS }}:
         - job: postman_tests_${{ replace(item, '-', '_') }}
-          displayName: 'Postman Tests for ${{ item }}'
-          pool: 
+          displayName: '${{ item }} postman'
+          pool:
             name: $(DEV_AGENT_POOL)
           variables:
             stageOutcome: 'Succeeded'
           steps:
-          - checkout: self
-            name: checkoutSourceCode
-            displayName: 'Checkout Source Code'
+            - checkout: self
+              name: checkoutSourceCode
+              displayName: 'Checkout Source Code'
 
-          - task: Bash@3
-            name: setPostmanVariables
-            displayName: 'Set and Print Postman Variables'
-            inputs:
-              targetType: 'inline'
-              script: |
-                echo "Setting variables..."
-                nameRepo=$(yq '.postman-test.nameRepo' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
-                dir=$(yq '.postman-test.dir' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
-                collectionName=$(yq '.postman-test.collectionName' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
-                envVariables=$(yq '.postman-test.envVariables' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+            - task: Bash@3
+              name: canRunPostmanTests
+              displayName: 'Can postman tests runs'
+              inputs:
+                targetType: 'inline'
+                script: |
+                  echo "🔨 Setting variables..."
+                  rootPostman=$(yq '.postman-test' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+                  runPostmanTests=$(yq '.postman-test.run' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
 
-                echo "Printing variables..."
-                echo "nameRepo: $nameRepo"
-                echo "dir: $dir"
-                echo "collectionName: $collectionName"
-                echo "envVariables: $envVariables"
+                  echo "rootPostman: $rootPostman"
+                  echo "runPostmanTests: $runPostmanTests"
 
-                # Function to check if a value is empty or "null"
-                is_valid() {
-                    [ ! -z "$1" ] && [ "$1" != "null" ]
-                }
+                  # Function to check if a value is empty or "null"
+                  is_valid() {
+                      [ ! -z "$1" ] && [ "$1" != "null" ]
+                  }
 
-                # Set Azure DevOps variables with checks
-                if is_valid "$nameRepo"; then
-                    echo "##vso[task.setvariable variable=nameRepo]$nameRepo"
-                else
-                    echo "##vso[task.logissue type=warning]nameRepo is empty or null"
+                  # Check if rootPostman is valid, runPostmanTests is valid and true
+                  if ! is_valid "$rootPostman" || ! is_valid "$runPostmanTests" || [ "$runPostmanTests" != "true" ]; then
+                      echo "##vso[task.logissue type=warning]Skipping Postman tests. Reason: tag postman not exists or run is false"
+                      echo "##vso[task.setvariable variable=runPostmanTest;isOutput=true]false"
+                      exit 0
+                  fi
+
+                  echo "All checks passed. Proceeding with Postman tests."
+                  echo "##vso[task.setvariable variable=runPostmanTest;isOutput=true]true"
+
+            - task: Bash@3
+              name: setupPostmanVariables
+              displayName: 'Setup and Print Postman Variables'
+              condition: and(succeeded(), eq(variables['canRunPostmanTests.runPostmanTest'], 'true'))
+              inputs:
+                targetType: 'inline'
+                script: |
+                  # If we're here, rootPostman and runPostmanTests are valid, so we proceed with other checks
+                  nameRepo=$(yq '.postman-test.nameRepo' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+                  dir=$(yq '.postman-test.dir' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+                  collectionName=$(yq '.postman-test.collectionName' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+                  envVariables=$(yq '.postman-test.envVariables' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+
+                  echo "Printing variables..."
+                  echo "nameRepo: $nameRepo"
+                  echo "dir: $dir"
+                  echo "collectionName: $collectionName"
+                  echo "envVariables: $envVariables"
+                  echo "POSTMAN_BRANCH: ${{ parameters.POSTMAN_BRANCH }}"
+
+                  # Function to check if a value is empty or "null"
+                  is_valid() {
+                      [ ! -z "$1" ] && [ "$1" != "null" ]
+                  }
+
+                  # Set Azure DevOps variables with checks
+                  if is_valid "$nameRepo"; then
+                      echo "##vso[task.setvariable variable=nameRepo]$nameRepo"
+                  else
+                      echo "##vso[task.logissue type=warning]nameRepo is empty or null"
+                  fi
+
+                  if is_valid "$dir"; then
+                      echo "##vso[task.setvariable variable=dir]$dir"
+                  else
+                      echo "##vso[task.logissue type=warning]dir is empty or null"
+                  fi
+
+                  if is_valid "$collectionName"; then
+                      echo "##vso[task.setvariable variable=collectionName]$collectionName"
+                  fi
+
+                  if is_valid "$envVariables"; then
+                      echo "##vso[task.setvariable variable=envVariables]$envVariables"
+                  fi
+
+                  if ! is_valid "$nameRepo" || ! is_valid "$dir" || ! is_valid "$collectionName" || ! is_valid "$envVariables"; then
+                      echo "##vso[task.logissue type=warning]One or more required variables are not set or are set to 'null'. Postman tests will be skipped."
+                      echo "##vso[task.setvariable variable=runPostmanTest;isOutput=false]false"
+                  else
+                      echo "All required variables are set and not null. Proceeding with the Postman tests."
+                      echo "##vso[task.setvariable variable=runPostmanTest;isOutput=true]true"
+                  fi
+
+            - task: Bash@3
+              name: runPostmanTests
+              displayName: 'Run Postman Tests'
+              condition: and(succeeded(), eq(variables['setupPostmanVariables.runPostmanTest'], 'true'))
+              inputs:
+                targetType: inline
+                script:  |
+                  echo "🖨️ Printing variables..."
+                  echo "nameRepo: $(nameRepo)"
+                  echo "dir: $(dir)"
+                  echo "collectionName: $(collectionName)"
+                  echo "envVariables: $(envVariables)"
+                  echo "POSTMAN_BRANCH: ${{ parameters.POSTMAN_BRANCH }}"
+
+                  echo "All required variables are set. Proceeding with Postman tests."
+
+                  echo "Cloning repository from branch: ${{ parameters.POSTMAN_BRANCH }}"
+
+                  git clone -b ${{ parameters.POSTMAN_BRANCH }} https://github.com/pagopa/$(nameRepo).git
+                  ls -la
+                  cd $(nameRepo)/$(dir)
+                  ls -la
+                  cat postman.txt
+
+                  # Here you would typically run your Postman tests
+                  # For example:
+                  # npm install -g newman
+                  # newman run $(collectionName) -e $(envVariables)
+
+            - bash: |
+                if [ "$(stageOutcome)" == "SucceededWithIssues" ]; then
+                  echo "##vso[task.logissue type=warning]Stage completed with issues, but will be marked as successful."
                 fi
-
-                if is_valid "$dir"; then
-                    echo "##vso[task.setvariable variable=dir]$dir"
-                else
-                    echo "##vso[task.logissue type=warning]dir is empty or null"
-                fi
-
-                if is_valid "$collectionName"; then
-                    echo "##vso[task.setvariable variable=collectionName]$collectionName"
-                else
-                    echo "##vso[task.logissue type=warning]collectionName is empty or null"
-                fi
-
-                if is_valid "$envVariables"; then
-                    echo "##vso[task.setvariable variable=envVariables]$envVariables"
-                else
-                    echo "##vso[task.logissue type=warning]envVariables is empty or null"
-                fi
-
-                if ! is_valid "$nameRepo" || ! is_valid "$dir" || ! is_valid "$collectionName" || ! is_valid "$envVariables"; then
-                    echo "##vso[task.logissue type=warning]One or more required variables are not set or are set to 'null'. Deployment will be stopped."
-                    echo "##vso[task.setvariable variable=varsSetSuccessfully;isOutput=true]false"
-                    echo "##vso[task.setvariable variable=stageOutcome;]SucceededWithIssues"
-                else
-                    echo "All required variables are set and not null. Proceeding with the deployment."
-                    echo "##vso[task.setvariable variable=varsSetSuccessfully;isOutput=true]true"
-                fi
-
-          - bash: |
-              echo "Printing variables..."
-              echo "nameRepo: $(nameRepo)"
-              echo "dir: $(dir)"
-              echo "collectionName: $(collectionName)"
-              echo "envVariables: $(envVariables)"
-              echo "POSTMAN_BRANCH: ${{ parameters.POSTMAN_BRANCH }}"
-
-              echo "All required variables are set. Proceeding with Postman tests."
-
-              echo "Cloning repository from branch: ${{ parameters.POSTMAN_BRANCH }}"
-
-              git clone -b ${{ parameters.POSTMAN_BRANCH }} https://github.com/pagopa/$(nameRepo).git
-              ls -la
-              cd $(nameRepo)/$(dir)
-              ls -la
-              cat postman.txt
-
-              # Here you would typically run your Postman tests
-              # For example:
-              # npm install -g newman
-              # newman run $(collectionName) -e $(envVariables)
-            name: runPostmanTests
-            displayName: 'Run Postman Tests'
-            condition: and(succeeded(), eq(variables['setPostmanVariables.varsSetSuccessfully'], 'true'))
-
-          - bash: |
-              if [ "$(stageOutcome)" == "SucceededWithIssues" ]; then
-                echo "##vso[task.logissue type=warning]Stage completed with issues, but will be marked as successful."
-              fi
-              echo "##vso[task.complete result=Succeeded;]"
-            name: forceStageSuccess
-            displayName: 'Force Stage Success'
-            condition: always()
+                echo "##vso[task.complete result=Succeeded;]"
+              name: forceStageSuccess
+              displayName: 'Force Stage Success'
+              condition: always()
