minor fix

diff --git a/.devops/deploy.yml b/.devops/deploy.yml
--- a/.devops/deploy.yml
+++ b/.devops/deploy.yml
@@ -42,8 +42,8 @@ stages:
 
       - bash: |
           changed_dirs_raw=$(git diff --name-only --diff-filter=d origin/main...HEAD | xargs -I {} dirname {} | sort -u | tr ' ' '\n') || { echo "Error: Failed to get changed directories."; exit 1; }
-          [ -z "$changed_dirs" ] && { echo "Error: No changed directories found."; exit 1; }
-          changed_dirs_list = $changed_dirs | tr ' ' '\n'
+          changed_dirs_raw = $changed_dirs
+          [ -z "$changed_dirs_list" ] && { echo "Error: No changed directories found."; exit 1; }
           echo $changed_dirs_list
 
           echo "---"
