debug

diff --git a/.devops/deploy.yml b/.devops/deploy.yml
--- a/.devops/deploy.yml
+++ b/.devops/deploy.yml
@@ -217,101 +217,99 @@ stages:
     condition: succeeded()
     jobs:
       - ${{ each item in parameters.APPS }}:
-        - deployment: postman_tests_${{ replace(item, '-', '_') }}
+        - job: postman_tests_${{ replace(item, '-', '_') }}
           displayName: 'Postman Tests for ${{ item }}'
-          environment: ${{ parameters.ENV }}
           pool: 
             name: $(DEV_AGENT_POOL)
-          strategy:
-            runOnce:
-              deploy:
-                steps:
-                - checkout: self
-                - task: Bash@3
-                  displayName: 'Set and Print Postman Variables'
-                  name: varsPostman
-                  inputs:
-                    targetType: 'inline'
-                    script: |
-                      echo "Setting variables..."
-                      nameRepo=$(yq '.postman-test.nameRepo' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
-                      dir=$(yq '.postman-test.dir' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
-                      collectionName=$(yq '.postman-test.collectionName' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
-                      envVariables=$(yq '.postman-test.envVariables' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+          variables:
+            stageOutcome: 'Succeeded'
+          steps:
+          - checkout: self
+          - task: Bash@3
+            displayName: 'Set and Print Postman Variables'
+            name: varsPostman
+            inputs:
+              targetType: 'inline'
+              script: |
+                echo "Setting variables..."
+                nameRepo=$(yq '.postman-test.nameRepo' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+                dir=$(yq '.postman-test.dir' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+                collectionName=$(yq '.postman-test.collectionName' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
+                envVariables=$(yq '.postman-test.envVariables' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{item}}/values.yaml)
 
-                      echo "Printing variables..."
-                      echo "nameRepo: $nameRepo"
-                      echo "dir: $dir"
-                      echo "collectionName: $collectionName"
-                      echo "envVariables: $envVariables"
+                echo "Printing variables..."
+                echo "nameRepo: $nameRepo"
+                echo "dir: $dir"
+                echo "collectionName: $collectionName"
+                echo "envVariables: $envVariables"
 
-                      # Function to check if a value is empty or "null"
-                      is_valid() {
-                          [ ! -z "$1" ] && [ "$1" != "null" ]
-                      }
+                # Function to check if a value is empty or "null"
+                is_valid() {
+                    [ ! -z "$1" ] && [ "$1" != "null" ]
+                }
 
-                      # Set Azure DevOps variables with checks
-                      if is_valid "$nameRepo"; then
-                          echo "##vso[task.setvariable variable=nameRepo]$nameRepo"
-                      else
-                          echo "##vso[task.logissue type=warning]nameRepo is empty or null"
-                      fi
+                # Set Azure DevOps variables with checks
+                if is_valid "$nameRepo"; then
+                    echo "##vso[task.setvariable variable=nameRepo]$nameRepo"
+                else
+                    echo "##vso[task.logissue type=warning]nameRepo is empty or null"
+                fi
 
-                      if is_valid "$dir"; then
-                          echo "##vso[task.setvariable variable=dir]$dir"
-                      else
-                          echo "##vso[task.logissue type=warning]dir is empty or null"
-                      fi
+                if is_valid "$dir"; then
+                    echo "##vso[task.setvariable variable=dir]$dir"
+                else
+                    echo "##vso[task.logissue type=warning]dir is empty or null"
+                fi
 
-                      if is_valid "$collectionName"; then
-                          echo "##vso[task.setvariable variable=collectionName]$collectionName"
-                      else
-                          echo "##vso[task.logissue type=warning]collectionName is empty or null"
-                      fi
+                if is_valid "$collectionName"; then
+                    echo "##vso[task.setvariable variable=collectionName]$collectionName"
+                else
+                    echo "##vso[task.logissue type=warning]collectionName is empty or null"
+                fi
 
-                      if is_valid "$envVariables"; then
-                          echo "##vso[task.setvariable variable=envVariables]$envVariables"
-                      else
-                          echo "##vso[task.logissue type=warning]envVariables is empty or null"
-                      fi
+                if is_valid "$envVariables"; then
+                    echo "##vso[task.setvariable variable=envVariables]$envVariables"
+                else
+                    echo "##vso[task.logissue type=warning]envVariables is empty or null"
+                fi
 
-                      if ! is_valid "$nameRepo" || ! is_valid "$dir" || ! is_valid "$collectionName" || ! is_valid "$envVariables"; then
-                          echo "##vso[task.logissue type=warning]One or more required variables are not set or are set to 'null'. Deployment will be stopped."
-                          echo "##vso[task.setvariable variable=varsSetSuccessfully;isOutput=true]false"
-                          echo "##vso[task.complete result=SucceededWithIssues;]"
-                      else
-                          echo "All required variables are set and not null. Proceeding with the deployment."
-                          echo "##vso[task.setvariable variable=varsSetSuccessfully;isOutput=true]true"
-                      fi
+                if ! is_valid "$nameRepo" || ! is_valid "$dir" || ! is_valid "$collectionName" || ! is_valid "$envVariables"; then
+                    echo "##vso[task.logissue type=warning]One or more required variables are not set or are set to 'null'. Deployment will be stopped."
+                    echo "##vso[task.setvariable variable=varsSetSuccessfully;isOutput=true]false"
+                    echo "##vso[task.setvariable variable=stageOutcome;]SucceededWithIssues"
+                else
+                    echo "All required variables are set and not null. Proceeding with the deployment."
+                    echo "##vso[task.setvariable variable=varsSetSuccessfully;isOutput=true]true"
+                fi
 
-                - bash: |
-                    echo "Printing variables..."
-                    echo "nameRepo: $(nameRepo)"
-                    echo "dir: $(dir)"
-                    echo "collectionName: $(collectionName)"
-                    echo "envVariables: $(envVariables)"
+          - bash: |
+              echo "Printing variables..."
+              echo "nameRepo: $(nameRepo)"
+              echo "dir: $(dir)"
+              echo "collectionName: $(collectionName)"
+              echo "envVariables: $(envVariables)"
 
-                    echo "All required variables are set. Proceeding with Postman tests."
+              echo "All required variables are set. Proceeding with Postman tests."
 
-                    git clone https://github.com/pagopa/$(nameRepo).git
-                    ls -la
-                    cd $(nameRepo)/$(dir)
-                    ls -la
-                    cat postman.txt
+              git clone https://github.com/pagopa/$(nameRepo).git
+              ls -la
+              cd $(nameRepo)/$(dir)
+              ls -la
+              cat postman.txt
 
-                    # Here you would typically run your Postman tests
-                    # For example:
-                    # npm install -g newman
-                    # newman run $(collectionName) -e $(envVariables)
-                  displayName: 'Run Postman Tests'
-                  condition: and(succeeded(), eq(variables['varsPostman.varsSetSuccessfully'], 'true'))
+              # Here you would typically run your Postman tests
+              # For example:
+              # npm install -g newman
+              # newman run $(collectionName) -e $(envVariables)
+            displayName: 'Run Postman Tests'
+            condition: and(succeeded(), eq(variables['varsPostman.varsSetSuccessfully'], 'true'))
 
-                - bash: |
-                    if [ "$(Agent.JobStatus)" == "SucceededWithIssues" ]; then
-                      echo "##vso[task.complete result=Succeeded;]"
-                    fi
-                  displayName: 'Set Job Status'
-                  condition: always()
-                  continueOnError: true
+          - bash: |
+              if [ "$(stageOutcome)" == "SucceededWithIssues" ]; then
+                echo "##vso[task.logissue type=warning]Stage completed with issues, but will be marked as successful."
+              fi
+              echo "##vso[task.complete result=Succeeded;]"
+            displayName: 'Force Stage Success'
+            condition: always()
 
 
